name: flint_dart
description: A minimal Dart backend framework by Eulogia Technologies.
version: 1.0.0
homepage: https://flintdart.eulogia.net
repository: https://github.com/eulogiatechnologies/flint_dart
issue_tracker: https://github.com/eulogiatechnologies/flint_dart/issues
environment:
  sdk: '>=3.2.0 <4.0.0'



# Add regular dependencies here.
dependencies:
  dart_jsonwebtoken: ^3.2.0
  crypto: ^3.0.6
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
executables:
  hot_reload: bin/hot_reload.dart
