name: flint_dart
description: A minimal Dart backend framework by Eulogia Technologies.
version: 1.0.0
homepage: https://flintdart.eulogia.net
repository: https://github.com/eulogiatechnologies/flint_dart
issue_tracker: https://github.com/eulogiatechnologies/flint_dart/issues

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  mysql1: ^0.20.0       # MySQL database driver
  crypto: ^3.0.6        # Cryptographic functions
  bcrypt: ^1.1.3        # Password hashing
  dart_jsonwebtoken: ^3.2.0  # JWT token handling

dev_dependencies:
  lints: ^5.0.0         # Dart lint rules
  test: ^1.24.0         # Testing framework

executables:
  flint: flint_cli 
  flint_hot: hot_reload # Hot reload executable